[project]
name = "02-rag-basic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.15.1",
    "jieba>=0.42.1",
    "langchain-text-splitters>=1.1.2",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=6.1.0",
    "unstructured>=0.27.10",
]
